service: db-service

plugins:
  - serverless-s3-deploy
  - serverless-functions-base-path
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ../../webpack.config.js
    includeModules: true

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  environment:
    PG_HOST: lesson4.cwnmiwlsfcrn.eu-west-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: lesson4
    PG_USERNAME: postgres
    PG_PASSWORD: 5354431Am

functions:
  createAndFillDb:
    handler: handler.createAndFillDb

  

