export const products = [
    {
        id: '6a5d2c9f-1709-414e-b1f0-0faae23c9b2d',
        name: 'Airpods Wireless Bluetooth Headphones',
        image: '/images/airpods.jpg',
        description:
            'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4,
        numReviews: 5,
    },
    {
        id: '5804cb94-cc98-431c-8195-b15695a7700d',
        name: 'iPhone 11 Pro 256GB Memory',
        image: '/images/phone.jpg',
        description:
            'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
        brand: 'Apple',
        category: 'Electronics',
        price: 599.99,
        countInStock: 10,
        rating: 3,
        numReviews: 7,
    },
    {
        id: '5580a2e7-1679-46ef-a425-2d626e1534d1',
        name: 'Cannon EOS 80D DSLR Camera',
        image: '/images/camera.jpg',
        description:
            'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
        brand: 'Cannon',
        category: 'Electronics',
        price: 929.99,
        countInStock: 0,
        rating: 4.5,
        numReviews: 4,
    },
    {
        id: '4df96f54-436c-45c4-abd8-c33f03e79d6d',
        name: 'Sony Playstation 4 Pro White Version',
        image: '/images/playstation.jpg',
        description:
            'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
        brand: 'Sony',
        category: 'Electronics',
        price: 399.99,
        countInStock: 10,
        rating: 5,
        numReviews: 1,
    },
    {
        id: '6881bc64-ce5d-4d14-876f-71a56254dab9',
        name: 'Logitech G-Series Gaming Mouse',
        image: '/images/mouse.jpg',
        description:
            'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
        brand: 'Logitech',
        category: 'Electronics',
        price: 49.99,
        countInStock: 7,
        rating: 3.5,
        numReviews: 2,
    },
    {
        id: '8d9e6530-4241-4d52-a039-9343755a9e1c',
        name: 'Amazon Echo Dot 3rd Generation',
        image: '/images/alexa.jpg',
        description:
            'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
        brand: 'Amazon',
        category: 'Electronics',
        price: 29.99,
        countInStock: 0,
        rating: 4.5,
        numReviews: 8,
    },
]

